# Generated by Django 5.1.3 on 2024-11-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mobile_no", models.CharField(max_length=10)),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("HR", "HR"),
                            ("Manager", "Manager"),
                            ("Sales", "Sales"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("courses", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="employee_images/")),
            ],
        ),
    ]
