# Generated by Django 5.1.3 on 2024-11-26 06:02

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_employee_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="mobile_no",
            new_name="mobile",
        ),
        migrations.AlterField(
            model_name="employee",
            name="courses",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("BTECH", "B.TECH"),
                    ("BSC", "BSC"),
                    ("MBA", "MBA"),
                    ("BCA", "BCA"),
                ],
                max_length=17,
            ),
        ),
    ]
