# Generated by Django 5.1.3 on 2024-11-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_mobile_no_employee_mobile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="image",
        ),
        migrations.AddField(
            model_name="employee",
            name="img_upload",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="courses",
            field=models.CharField(max_length=200),
        ),
    ]
