# Generated by Django 5.1.3 on 2024-11-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_employee_image_employee_img_upload_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="courses",
            field=models.CharField(
                choices=[("MCA", "MCA"), ("BCA", "BCA"), ("BSC", "BSC")], max_length=200
            ),
        ),
    ]
